name: Release Obsidian Progressbar

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-progressbar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          cp ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}-${{ github.ref }}.zip
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag: ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: "./${{ env.PLUGIN_NAME }}-${{ github.ref }}.zip,main.js,manifest.json,styles.css"
